// examples/svelte-example/src/App.svelte
<script>
  import LinkPreview from "./components/LinkPreview.svelte";

  let url = "https://matrix.org";
  let idx = 1;

  const updateUrl = () => {
    const urls = [
      "https://matrix.org",
      "https://www.cloudflare.com/",
      "https://en.wikipedia.org",
    ];
    url = urls[idx];

    if (idx + 1 < urls.length) {
      idx += 1;
    } else {
      idx = 0;
    }
  };
</script>

<main>
  <h1>Svelte link preview example</h1>
  <p>
    This is an example of using link previews with dynamically rendered content.
    Click <button on:click={updateUrl}>update url</button> to switch out the
    components's <code>href</code> and update the preview:
  </p>
  <p>
    <LinkPreview href={url}>This is a link to {url}</LinkPreview>
  </p>
</main>

<style>
  main {
    max-width: 600px;
    margin: 0 auto;
  }

  p {
    margin: 2rem 0;
  }
</style>

// examples/react-example/src/App.js
import "./App.css";
import { useState } from "react";
import LinkPreview from "./components/LinkPreview";

function App() {
  const [url, setUrl] = useState("https://matrix.org");
  const [idx, setIdx] = useState(1);

  const updateUrl = () => {
    const urls = [
      "https://matrix.org",
      "https://www.cloudflare.com/",
      "https://en.wikipedia.org",
    ];
    setUrl(urls[idx]);

    if (idx + 1 < urls.length) {
      setIdx(idx + 1);
    } else {
      setIdx(0);
    }
  };

  return (
    <div className="App">
      <h1>React link preview example</h1>
      <p>
        This is an example of using link previews with dynamically rendered
        content. Click <button onClick={updateUrl}>update url</button> to switch
        out the components's <code>href</code> and update the preview:{" "}
      </p>
      <p>
        <LinkPreview href={url}>This is a link to {url}</LinkPreview>
      </p>
    </div>
  );
}

export default App;
