// examples/react-example/src/components/LinkPreview.jsx
import { useRef, useEffect } from "react";
import { linkPreview } from "link-previews";

function LinkPreview(props) {
  const linkRef = useRef(null);

  // add a link preview to the element
  useEffect(() => {
    if (linkRef) {
      linkPreview(linkRef.current, {
        backend: "http://localhost:8787",
      });
    }
  });

  return (
    <a
      ref={linkRef}
      href={props.href}
      target="_blank"
      rel="noopener noreferrer"
    >
      {props.children}
    </a>
  );
}

export default LinkPreview;

// examples/svelte-example/src/components/LinkPreview.svelte
<script>
  import { linkPreview } from "link-previews";
  import { onMount } from "svelte";

  export let href;

  let thisElt;

  onMount(() => {
    linkPreview(thisElt, { backend: "http://localhost:8787" });
  });
</script>

<a bind:this={thisElt} {href} target="_blank" rel="noopener noreferrer">
  <slot />
</a>
